name: Conversor de memòries de Softcatalà per Qt Linguist.

on:
  push:
    branches:
      - main

jobs:
  descarregar-convertir-i-pujar:
    permissions: write-all
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - name: Carregar el repositori
      uses: actions/checkout@v3

    - name: Preparar el Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instal·lar dependències
      run: pip install docopt bs4 thefuzz

    - name: Obtenir tmx2qph.py
      run: |
        wget https://raw.githubusercontent.com/Eloitor/tmx2qph/master/TMX2QPH.py

    - name: Descarregar els fitxers TMX
      run: |
        wget https://static.softcatala.org/memories/abiword-tm.tmx.zip

    - name: Descomprimir els fitxers TMX
      run: |
        unzip abiword-tm.tmx.zip

    - name: Convertir el fitxer TMX a QPH (versionat)
      run: |
        python TMX2QPH.py abiword-tm.tmx --output=abiword-$(date +%s).qph

    - name: Publicar els fitxers QPH com a artefactes
      uses: actions/upload-artifact@v3
      with:
        name: qph-files
        path: |
          *.qph

    - name: Publicar els fitxers QPH a git
      env: 
        CI_COMMIT_MESSAGE: Actualizació automàtica per CI
        CI_COMMIT_AUTHOR: Github CI
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "eloitor@users.noreply.github.com"
        git add *.qph
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
